### ISSUE TITLE
[enhancement] Splash Screen & Login Screen

### ISSUE THREAD

**Issue by as280093** [CarlosEsco/MangaDex#18]
Here is the idea of splash screen 
background hex color **#F39424**
![splash screen](https://user-images.githubusercontent.com/25240839/55809236-2d076680-5b03-11e9-8743-dda1f77c495e.png)

Login screen after splash screen if user is new 
![login](https://user-images.githubusercontent.com/25240839/55811168-54136780-5b06-11e9-9f6a-db05cd457fe2.png)

Sign Up will open chrome sign up page of mangadex
if this is Skipped then user can login in from settings 

![art](https://user-images.githubusercontent.com/25240839/55853230-c2dfd780-5b7d-11e9-92de-be52f7f87780.png)

**Comment by CarlosEsco** [comment]
For now i am gonna close this.  Will revisit login ui after a far in the future u.i update
