### ISSUE TITLE
[Feature] Support 2FA

### ISSUE THREAD

**Issue by AviKav** [CarlosEsco/MangaDex#65]
A question is whether the 2FA field should be should be shown by default, hidden behind a toggle, or only shown after MD responds that one is needed (the site's current behavior).

**Comment by CarlosEsco** [comment]
Question if i enable 2FA on account can i disable later?  i might be able to test some options when i have some time.

**Comment by AviKav** [comment]
Yeah
![image](https://user-images.githubusercontent.com/18518861/56270615-87389680-60c4-11e9-9dbf-3f1248c75d4c.png)

**Comment by CarlosEsco** [comment]
added to 1.0.4
