### ISSUE TITLE
[BUG] fix launcher icon 

### ISSUE THREAD

**Issue by as280093** [CarlosEsco/MangaDex#70]
**Describe the bug**
the rounded icon is provided so add square icon too 

here is the squared icon 
https://github.com/inorichi/tachiyomi-extensions/tree/master/src/all/mangadex/res

**Comment by CarlosEsco** [comment]
I am gonna make the icon adaptive and keep the round as the main one for Android versions that don't support adaptive icons

**Comment by as280093** [comment]
ok i will try making one

**Comment by as280093** [comment]
![Artboard 1xxxhddpi](https://user-images.githubusercontent.com/25240839/56468495-f9093b00-644a-11e9-8424-f3a75924cd0e.png)
![Artboard 1xxxhdpi](https://user-images.githubusercontent.com/25240839/56468509-19d19080-644b-11e9-8a10-973f54c22037.png)



try this for preview 
first time making icon by following 90% of the guidelines
https://adapticon.tooo.io/#/bg=https://user-images.githubusercontent.com/25240839/56468495-f9093b00-644a-11e9-8424-f3a75924cd0e.png/fg=https://user-images.githubusercontent.com/25240839/56468509-19d19080-644b-11e9-8a10-973f54c22037.png

**Comment by CarlosEsco** [comment]
fixed in 1.0.4
